trigger:
        - main

pool:
          vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
          imageName: 'gokul3r/gokulrepo1'
          tag: '$(Build.BuildId)'

steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile
        - task: Docker@2
          displayName: Push image
          inputs:
           containerRegistry: |
             $(dockerHub)
           repository: $(imageName)
           command: push
           tags: |
            $(tag)